using System;
using System.Linq;
using CustomPlayerEffects;
using LabApi.Features.Wrappers;
using PlayerRoles;
using PlayhousePlugin.Runtime;
using UnityEngine;

namespace PlayhousePlugin.GameModes;

public sealed class SillySundayService
{
    private readonly PluginRuntime runtime; private readonly System.Random random=new();
    public bool IsEnabled{get;set;} public bool NerfWar{get;private set;} public bool InstantRevive{get;private set;} public bool RandomRevive{get;private set;} public bool Slaughterhouse{get;private set;} public bool SugarRush{get;private set;} public bool OhFiveRescue{get;private set;} public Player? OhFivePlayer{get;private set;} public bool OhFiveDied{get;private set;} public RoleTypeId InfectionRole{get;private set;}=RoleTypeId.None;
    public SillySundayService(PluginRuntime runtime)=>this.runtime=runtime;
    public void Reset(){NerfWar=InstantRevive=RandomRevive=Slaughterhouse=SugarRush=OhFiveRescue=OhFiveDied=false;OhFivePlayer=null;InfectionRole=RoleTypeId.None;}
    public bool Start(string mode,out string response)
    {
        if(!IsEnabled){response="Silly Sunday is disabled.";return false;}mode=mode.ToLowerInvariant();
        switch(mode){case"nerfwar1":StartNerf(ItemType.GunCOM15,ItemType.Ammo9x19,RoleTypeId.Scientist,RoleTypeId.ClassD);break;case"nerfwar2":StartNerf(ItemType.GunFSP9,ItemType.Ammo9x19,RoleTypeId.Scientist,RoleTypeId.ClassD);break;case"nerfwar3":StartNerf(ItemType.GunCrossvec,ItemType.Ammo9x19,RoleTypeId.FacilityGuard,RoleTypeId.ClassD);break;case"nerfwar4":StartNerf(ItemType.GunLogicer,ItemType.Ammo762x39,RoleTypeId.NtfPrivate,RoleTypeId.ClassD);runtime.Schedule(120,()=>{foreach(Player p in Player.ReadyList.Where(p=>p.Role==RoleTypeId.Spectator))p.SetRole(RoleTypeId.Scp939);});break;case"sugarrush":SugarRush=true;foreach(Player p in Player.ReadyList)p.EnableEffect<MovementBoost>(30,1800);Server.SendBroadcast("<color=yellow><b>Sugar Rush!</b></color>",10);break;case"instantrevive":InstantRevive=true;ConvertScpsTo049();Server.SendBroadcast("<color=yellow><b>Instant Revive: SCP-049 kills become zombies.</b></color>",10);break;case"randomrevive":RandomRevive=true;ConvertScpsTo049();Server.SendBroadcast("<color=yellow><b>Plague Doctor's Beckoning: revived bodies become random SCPs.</b></color>",10);break;case"slaughterhouse":StartSlaughterhouse();break;case"05rescue":StartOhFiveRescue();break;case"173":case"173infection":ToggleInfection(RoleTypeId.Scp173);break;case"096":case"096infection":ToggleInfection(RoleTypeId.Scp096);break;case"049":case"049infection":ToggleInfection(RoleTypeId.Scp049);break;case"939":case"939infection":ToggleInfection(RoleTypeId.Scp939);break;case"106":case"106infection":ToggleInfection(RoleTypeId.Scp106);break;default:response="Unknown Silly Sunday event.";return false;}response=$"Silly Sunday event '{mode}' started/toggled.";return true;
    }
    private void StartNerf(ItemType gun,ItemType ammo,RoleTypeId first,RoleTypeId second){Reset();NerfWar=true;Cleanup();Player[] players=Player.ReadyList.ToArray();for(int i=0;i<players.Length;i++){Player p=players[i];RoleTypeId role=i%2==0?first:second;p.SetRole(role);runtime.Schedule(.6f,()=>{p.ClearInventory();p.AddItem(gun);p.SetAmmo(ammo,10);});}Server.SendBroadcast("<color=orange><b>Nerf War! Eliminate the other team.</b></color>",10);}
    private void StartSlaughterhouse(){Reset();Slaughterhouse=true;Player[] all=Player.ReadyList.OrderBy(_=>random.Next()).ToArray();int bosses=Math.Min(5,Math.Max(1,all.Length/4));for(int i=0;i<all.Length;i++){Player p=all[i];p.SetRole(i<bosses?RoleTypeId.Scientist:RoleTypeId.ChaosConscript);runtime.Schedule(.6f,()=>{if(p.Role==RoleTypeId.Scientist){GiveHeavyLoadout(p);p.MaxHealth=5000;p.Health=5000;}else{p.ClearInventory();p.AddItem(ItemType.GunLogicer);p.AddItem(ItemType.Medkit);p.AddItem(ItemType.Medkit);p.AddItem(ItemType.KeycardChaosInsurgency);p.SetAmmo(ItemType.Ammo762x39,450);}});}Server.SendBroadcast("<color=yellow><b>Slaughterhouse!</b></color>",10);}
    private void StartOhFiveRescue(){Reset();OhFiveRescue=true;Player[] all=Player.ReadyList.OrderBy(_=>random.Next()).ToArray();if(all.Length==0)return;Player o5=all[0];OhFivePlayer=o5;o5.SetRole(RoleTypeId.Scientist);runtime.Schedule(.6f,()=>{GiveHeavyLoadout(o5);o5.MaxHealth=200;o5.Health=200;o5.Scale=Vector3.one*.9f;});for(int i=1;i<all.Length;i++){Player p=all[i];bool mtf=i<=Math.Min(9,all.Length-1);p.SetRole(mtf?RoleTypeId.NtfCaptain:RoleTypeId.ChaosConscript);runtime.Schedule(.6f,()=>{if(mtf){GiveHeavyLoadout(p);p.MaxHealth=450;p.Health=450;}else{p.ClearInventory();p.AddItem(ItemType.GunLogicer);p.AddItem(ItemType.Medkit);p.AddItem(ItemType.KeycardChaosInsurgency);p.SetAmmo(ItemType.Ammo762x39,150);}});}Server.SendBroadcast("<color=yellow><b>O5 Rescue: escort or eliminate O5-13.</b></color>",10);}
    private static void GiveHeavyLoadout(Player p){p.ClearInventory();p.AddItem(ItemType.Medkit);p.AddItem(ItemType.Medkit);p.AddItem(ItemType.Medkit);p.AddItem(ItemType.GunLogicer);p.AddItem(ItemType.GunE11SR);p.AddItem(ItemType.GunCrossvec);p.AddItem(ItemType.Radio);p.AddItem(ItemType.KeycardO5);p.SetAmmo(ItemType.Ammo9x19,500);p.SetAmmo(ItemType.Ammo556x45,400);p.SetAmmo(ItemType.Ammo762x39,750);}
    private void ConvertScpsTo049(){foreach(Player p in Player.ReadyList.Where(p=>p.Team==Team.SCPs).ToArray())p.SetRole(RoleTypeId.Scp049);}
    private void ToggleInfection(RoleTypeId role)=>InfectionRole=InfectionRole==role?RoleTypeId.None:role;
    public void OnDeath(Player victim,Player? killer){if(!IsEnabled)return;Vector3 pos=victim.Position;if(OhFiveRescue){if(victim==OhFivePlayer){Server.SendBroadcast("The O5 has died. Chaos wins! Facility wipe initiated!",10);Warhead.Start();Warhead.IsLocked=true;OhFiveDied=true;OhFivePlayer=null;}if(OhFiveDied){victim.SendBroadcast("<i>Respawning in 10 seconds...</i>",10);runtime.Schedule(10,()=>{victim.SetRole(RoleTypeId.ChaosConscript);victim.SendBroadcast("<color=yellow><i>Welcome back...</i>\n<b>Kill the remaining foundation personnel.</b></color>",6);});return;}}if(InstantRevive&&killer?.Role==RoleTypeId.Scp049&&killer!=victim)runtime.Schedule(.2f,()=>{victim.SetRole(RoleTypeId.Scp0492);runtime.Schedule(.4f,()=>victim.Position=killer.Position);});else if(InfectionRole!=RoleTypeId.None&&killer?.Role==InfectionRole)runtime.Schedule(.2f,()=>{victim.SetRole(InfectionRole);runtime.Schedule(.4f,()=>victim.Position=killer.Position);});else if(Slaughterhouse)runtime.Schedule(10,()=>{victim.SetRole(RoleTypeId.ChaosConscript);runtime.Schedule(.5f,()=>victim.Position=pos);});}
    public RoleTypeId GetReviveRole()=>RandomRevive?new[]{RoleTypeId.Scp096,RoleTypeId.Scp106,RoleTypeId.Scp173,RoleTypeId.Scp939}[random.Next(4)]:RoleTypeId.Scp0492;
    private static void Cleanup(){foreach(Pickup p in Pickup.List.ToArray())if(!p.IsLocked)p.Destroy();foreach(Ragdoll r in Ragdoll.List.ToArray())r.Destroy();}
}
